"""
Django settings for iipdash project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from email.utils import getaddresses
from pathlib import Path
from urllib.parse import urljoin

from django.utils.translation import gettext_lazy as _

import environ
from corsheaders.defaults import default_headers as cors_default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.append(str(BASE_DIR / "apps"))

env = environ.Env()
env.read_env(str(BASE_DIR / ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-7b%v^$@s8ct1c)yx^dr8-@h=oqr&%66q&9!)owdb)fc=adtb2",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)

# https://docs.djangoproject.com/en/5.1/ref/settings/#allowed-hosts
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

INTERNAL_IPS = env.list("INTERNAL_IPS", default=["127.0.0.1"])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_celery_results",
    "django_celery_beat",
    "treebeard",
    "django_countries",
    "import_export",
    "allauth",
    "allauth.account",
    "rest_framework",
    "rest_framework_gis",
    "oauth2_provider",
    "django_filters",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "corsheaders",
    "crispy_forms",
    "crispy_bootstrap5",
    "core",
    "users",
    "catalog",
    "administrative",
    "demographics",
    "education",
    "health",
    "infrastructure",
    "hazards",
    "dashboards",
    "debug_toolbar",
    "active_link",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "iipdash.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "iipdash.context_processors.site",
            ],
        },
    },
]

WSGI_APPLICATION = "iipdash.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# https://docs.djangoproject.com/en/5.1/ref/settings/#test

DATABASES = {
    "default": {
        "ENGINE": env("DATABASE_ENGINE", default="django.contrib.gis.db.backends.postgis"),
        "NAME": env("DATABASE_NAME", default="iipdash"),
        "USER": env("DATABASE_USER", default="iipdash"),
        "PASSWORD": env("DATABASE_PASSWORD", default="iipdash"),
        "HOST": env("DATABASE_HOST", default="localhost"),
        "PORT": env.int("DATABASE_PORT", default=5432),
        "CONN_MAX_AGE": env.int("DATABASE_CONN_MAX_AGE", default=0),
        "ATOMIC_REQUESTS": env.bool("DATABASE_ATOMIC_REQUESTS", default=True),
        "CONN_HEALTH_CHECKS": env.bool("CONN_HEALTH_CHECKS", default=False),
        "TEST": {
            "NAME": env("TEST_DATABASE_NAME", default="test_iipdash"),
            "USER": env("TEST_DATABASE_USER", default="test_iipdash"),
            "PASSWORD": env("TEST_DATABASE_PASSWORD", default="test_iipdash"),
            "HOST": env("TEST_DATABASE_HOST", default="localhost"),
            "PORT": env.int("TEST_DATABASE_PORT", default=5432),
            "MIGRATE": env.bool("TEST_DATABASE_MIGRATE", default=True),
        },
    }
}

# Cache

CACHES = {
    "default": {
        "BACKEND": env("CACHE_DEFAULT_BACKEND", default="django.core.cache.backends.redis.RedisCache"),
        "LOCATION": env("CACHE_DEFAULT_LOCATION", default="redis://127.0.0.1:6379"),
        "KEY_PREFIX": env("CACHE_DEFAULT_KEY_PREFIX", default="iipdash"),
        "TIMEOUT": env.int("CACHE_DEFAULT_TIMEOUT", default=300),
        "VERSION": env.int("CACHE_DEFAULT_VERSION", default=1),
    }
}

#: Timeouts for various of cache categories
CACHE_TIMEOUTS = {
    "default": env.int("CACHE_TIMEOUT_DEFAULT", default=60 * 5),  # 5 minutes
    "mvt": env.int("CACHE_TIMEOUT_MVT", default=60 * 60 * 24),  # 1 day
}

#: Name of cache to be used for vector tiles
CACHE_MVT_ALIAS = env("CACHE_MVT_ALIAS", default="default")

# Auth

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Password hashers
# https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-PASSWORD_HASHERS
# https://docs.djangoproject.com/en/5.1/topics/auth/passwords/
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

LOGIN_URL = "/accounts/login/"

LOGIN_REDIRECT_URL = "/"

ACCOUNT_LOGIN_METHODS = {"username", "email"}

ACCOUNT_ADAPTER = "users.adapters.DefaultAccountAdapter"

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE", default="en-us")

TIME_ZONE = env("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True

# Countries
# https://github.com/SmileyChris/django-countries?tab=readme-ov-file#customize-the-country-list
COUNTRIES_ONLY = [("CD", _("Democratic Republic of the Congo")), "MW", "ZM"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# https://docs.djangoproject.com/en/5.1/howto/static-files/deployment/

STATICFILES_DIRS = env.list(
    "STATICFILES_DIRS",
    default=[
        BASE_DIR / "static",
        BASE_DIR / "assets/dist",
    ],
)

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

STATIC_URL = env("STATIC_URL", default="/static/")

STATIC_ROOT = env("STATIC_ROOT", default=(BASE_DIR / "static_root"))

MEDIA_URL = env("MEDIA_URL", default="/media/")

MEDIA_ROOT = env("MEDIA_ROOT", default=str(BASE_DIR / "media_root"))

STORAGES = {
    "default": {
        "BACKEND": env("DEFAULT_FILE_STORAGE", default="django.core.files.storage.FileSystemStorage"),
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": env("STATICFILES_STORAGE", default="django.contrib.staticfiles.storage.StaticFilesStorage"),
        "OPTIONS": {},
    },
}

#: A URL path prefix for media files if ``ProtectedFileSystemStorage`` is used.
MEDIA_PROTECTED_URL = env("MEDIA_PROTECTED_URL", default="/x-media/")

#: A URL for handling internal redirects in nginx if ``ProtectedFileSystemStorage`` is used.
MEDIA_INTERNAL_URL = env("MEDIA_INTERNAL_URL", default="/media/")

_MEDIA_IS_PROTECTED = STORAGES["default"]["BACKEND"] == "core.files.ProtectedFileSystemStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Site

SITE_NAME = env("SITE_NAME", default="Infrastructure Mapping Platform")

SITE_URL = env("SITE_URL", default="https://digitalinfraplanning.org")

SITE_TAGLINE = env("SITE_TAGLINE", default="Integrated Infrastructure Planning (IIP) Dashboard")

SITE_API_NAME = env("SITE_API_NAME", default=f"{SITE_NAME} API")

SITE_API_URL = env("SITE_API_URL", default="/api")

# Admin site

ADMIN_SITE_NAME = env("ADMIN_SITE_HEADER", default=SITE_NAME)

ADMIN_SITE_HEADER = env("ADMIN_SITE_HEADER", default=SITE_NAME)

ADMIN_INDEX_TITLE = env("ADMIN_INDEX_TITLE", default="Administration")


# Email

EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")

EMAIL_FILE_PATH = env("EMAIL_FILE_PATH", default=None)

EMAIL_HOST = env("EMAIL_HOST", default="localhost")

EMAIL_PORT = env.int("EMAIL_PORT", default=25)

EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")

EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=30)

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="")

SERVER_EMAIL = env("SERVER_EMAIL", default="")

ADMINS = getaddresses([env("ADMINS", default="")])


# SSL & Security middleware

if env("SECURE_PROXY_SSL_HEADER", default=None):
    SECURE_PROXY_SSL_HEADER = env("SECURE_PROXY_SSL_HEADER").split()[:2]

if env("SECURE_SSL_REDIRECT", default=None):
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT")

if env("CSRF_COOKIE_SECURE", default=None):
    CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE")

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

if env("SECURE_HSTS_SECONDS", default=None):
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS")

SECURE_REFERRER_POLICY = env("SECURE_REFERRER_POLICY", default="strict-origin-when-cross-origin")


# REST framework settings

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": env("API_PAGE_SIZE", default=100),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "SEARCH_PARAM": "q",
    "ORDERING_PARAM": "ordering",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# REST framework GIS settings
BBOX_PARAM = env("BBOX_PARAM", default="in_bbox")
TILE_PARAM = env("TILE_PARAM", default="in_tile")
POINT_PARAM = env("POINT_PARAM", default="point")
DIST_PARAM = env("DIST_PARAM", default="radius")


SPECTACULAR_SETTINGS = {
    "TITLE": SITE_API_NAME,
    "DESCRIPTION": "",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PUBLIC": False,
    "SERVERS": [
        {
            "url": "/api",
            "description": "Default API server",
        },
    ],
    "SCHEMA_PATH_PREFIX": "/api",
    "SCHEMA_PATH_PREFIX_TRIM": True,
    "REDOC_DIST": "SIDECAR",
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    # UI settings for handling large responses
    "SWAGGER_UI_SETTINGS": {
        "syntaxHighlight": False,
        "displayRequestDuration": True,
    },
}


# CORS

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])

CORS_ALLOWED_ORIGIN_REGEXES = env.list("CORS_ALLOWED_ORIGIN_REGEXES", default=[])

CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG)

CORS_ALLOW_HEADERS = env.list("CORS_ALLOW_HEADERS", default=cors_default_headers)


# celery

CELERY_TIMEZONE = env("CELERY_TIMEZONE", default=TIME_ZONE)

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://")

CELERY_BROKER_CONNECTION_MAX_RETRIES = env.int("CELERY_BROKER_CONNECTION_MAX_RETRIES", default=5)

CELERY_ACCEPT_CONTENT = env.list("CELERY_ACCEPT_CONTENT", default=["json"])

CELERY_TASK_SERIALIZER = env("CELERY_TASK_SERIALIZER", default="json")

CELERY_RESULT_SERIALIZER = env("CELERY_RESULT_SERIALIZER", default="json")

CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="django-db")

CELERY_RESULT_EXTENDED = env.bool("CELERY_RESULT_EXTENDED", default=True)

# https://docs.celeryq.dev/en/v5.4.0/userguide/configuration.html#result-expires
CELERY_RESULT_EXPIRES = env.int("CELERY_RESULT_EXPIRES", default=60 * 60 * 24 * 30)  # defaults 1 month

CELERY_TASK_TRACK_STARTED = env.bool("CELERY_TASK_TRACK_STARTED", default=True)

CELERY_BEAT_SCHEDULER = env("CELERY_BEAT_SCHEDULER", default="django_celery_beat.schedulers:DatabaseScheduler")

CELERY_FLOWER_BASIC_AUTH = env("CELERY_FLOWER_BASIC_AUTH", default=None)

# Crispy forms

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# Administrative

ADMINISTRATIVE_AREAS_SIMPLIFICATION_TOLERANCE = env.float("ADMINISTRATIVE_AREAS_SIMPLIFICATION_TOLERANCE", default=1.0)


# Demographics

RELATIVE_WEALTH_INDEX_RESOLUTION = env.float("RELATIVE_WEALTH_INDEX_RESOLUTION", default=2400.0)  # 2.4 KM

# Raster tiles

TILES_ROOT = env("TILES_ROOT", default=str(Path(MEDIA_ROOT) / "tiles"))

if _MEDIA_IS_PROTECTED:
    _TILES_DEFAULT_BASE_URL = MEDIA_PROTECTED_URL
else:
    _TILES_DEFAULT_BASE_URL = MEDIA_URL

TILES_URL = env("TILES_URL", default=urljoin(_TILES_DEFAULT_BASE_URL, "tiles/"))

GDAL2TILES_PROCESSES = env.int("GDAL2TILES_PROCESSES", default=1)

# Mapbox
MAPBOX_STYLE_ID = env("MAPBOX_STYLE_ID", default="mapbox/light-v11")
MAPBOX_ACCESS_TOKEN = env("MAPBOX_ACCESS_TOKEN", default="")

# Map display
MAP_DEFAULT_CENTER = env.list("MAP_DEFAULT_CENTER", cast=float, default=[24.5, -6.5])

MAP_DEFAULT_ZOOM = env.int("MAP_DEFAULT_ZOOM", default=5)

MAP_DEFAULT_BBOX = env.list(
    "MAP_DEFAULT_BBOX",
    cast=float,
    default=[12.20152855, -18.079176286999903, 35.9150466920001, 5.386097909000106],
)

BASEMAP_URL = env(
    "BASEMAP_URL",
    default=f"https://api.mapbox.com/styles/v1/{MAPBOX_STYLE_ID}/tiles/256/{{z}}/{{x}}/{{y}}?access_token={MAPBOX_ACCESS_TOKEN}",  # noqa
)

BASEMAP_ATTRIBUTION = env(
    "BASEMAP_ATTRIBUTION",
    default='&copy; <a href="https://www.openstreetmap.org/" target="_blank" class="text-muted">'
    'OpenStreetMap</a> contributors, <a href="https://leafletjs.com" class="text-muted">',
)


# Analytics

GOOGLE_ANALYTICS_TAG_ID = env("GOOGLE_ANALYTICS_TAG_ID", default="")


# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[%(server_time)s] %(message)s",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
        },
        "console_debug_false": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "logging.StreamHandler",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "console_debug_false", "mail_admins"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security.DisallowedHost": {
            "handlers": ["console_debug_false"],
            "level": "CRITICAL",
            "propagate": False,
        },
    },
}
